In [46]:
import pandas as pd

In [47]:
wf_path = "../data/workflow-connections_Feb_22_1.csv"

In [48]:
wf_frame = pd.read_csv(wf_path, sep="|", header=None)

/home/anupkumar/anaconda3/envs/tool_prediction_gru_wc/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0,2,5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [49]:
wf_frame

,0,1,2,3,4,5,6,7,8,9,10
0,wf_id,wf_updated,in_id,...,in_tool_v,out_id,...,out_tool_v,published,deleted,has_errors
1,--------+------------+---------+--------------...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2013-02-07,5,Grep1 ...,1.0.1,7,Remove beginning1 ...,1.0.0,f,t,f
3,3,2013-02-07,6,Cut1 ...,1.0.1,8,addValue ...,1.0.0,f,t,f
4,3,2013-02-07,7,Remove beginning1 ...,1.0.0,6,Cut1 ...,1.0.1,f,t,f
...,...,...,...,...,...,...,...,...,...,...,...
2412941,134921,2022-02-15,1.9924e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmom...,0.38.1,f,f,f
2412942,134921,2022-02-15,1.99240e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmom...,0.38.1,f,f,f
2412943,134921,2022-02-15,1.99241e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmom...,0.38.1,f,f,f
2412944,134921,2022-02-15,1.99241e+06,...,,1.99236e+06,toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/...,2.4.2+galaxy0,f,f,f
2412945,(2412943 rows),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
wf_frame_1 = wf_frame[1:len(wf_frame.index)-1]

In [51]:
wf_frame_1 = wf_frame_1[1:]
wf_frame_1

,0,1,2,3,4,5,6,7,8,9,10
2,3,2013-02-07,5,Grep1 ...,1.0.1,7,Remove beginning1 ...,1.0.0,f,t,f
3,3,2013-02-07,6,Cut1 ...,1.0.1,8,addValue ...,1.0.0,f,t,f
4,3,2013-02-07,7,Remove beginning1 ...,1.0.0,6,Cut1 ...,1.0.1,f,t,f
5,3,2013-02-07,7,Remove beginning1 ...,1.0.0,9,Cut1 ...,1.0.1,f,t,f
6,3,2013-02-07,8,addValue ...,1.0.0,11,Paste1 ...,1.0.0,f,t,f
...,...,...,...,...,...,...,...,...,...,...,...
2412940,134921,2022-02-15,1.9924e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/iuc/filter_tabul...,2.0.0,f,f,f
2412941,134921,2022-02-15,1.9924e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmom...,0.38.1,f,f,f
2412942,134921,2022-02-15,1.99240e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmom...,0.38.1,f,f,f
2412943,134921,2022-02-15,1.99241e+06,...,,1.99235e+06,toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmom...,0.38.1,f,f,f
2412944,134921,2022-02-15,1.99241e+06,...,,1.99236e+06,toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/...,2.4.2+galaxy0,f,f,f

In [53]:
wf_frame_1 = wf_frame_1.sample(frac=1)
wf_frame_1

,0,1,2,3,4,5,6,7,8,9,10
1910966,72418,2020-12-04,1018284,toolshed.g2.bx.psu.edu/repos/iuc/anndata_mani...,0.6.22.post1+galaxy1,1018287,toolshed.g2.bx.psu.edu/repos/iuc/scanpy_plot/...,1.4.4.post1+galaxy1,f,f,f
459259,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
1083589,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
252642,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
6821,887,2014-03-14,15219,...,,15230,toolshed.g2.bx.psu.edu/repos/devteam/fastqc/f...,,f,t,
...,...,...,...,...,...,...,...,...,...,...,...
1592784,21747,2018-12-18,331828,...,,331801,toolshed.g2.bx.psu.edu/repos/iuc/stacks_procr...,1.46.0,f,f,t
1590874,21600,2018-12-17,328839,toolshed.g2.bx.psu.edu/repos/galaxyp/openms_m...,2.2.0,328835,toolshed.g2.bx.psu.edu/repos/galaxyp/openms_p...,2.2.0,f,f,f
1474236,5488,2016-07-29,81677,toolshed.g2.bx.psu.edu/repos/devteam/get_flan...,1.0.0,81707,toolshed.g2.bx.psu.edu/repos/devteam/join/gop...,1.0.0,f,t,f
1713787,39694,2019-11-21,597867,toolshed.g2.bx.psu.edu/repos/devteam/bamtools...,2.4.1,597868,toolshed.g2.bx.psu.edu/repos/iuc/umi_tools_co...,0.5.3.2,f,f,f
2158410,105860,2021-08-14,1556606,...,,1556612,toolshed.g2.bx.psu.edu/repos/devteam/fastqc/f...,0.72+galaxy1,f,f,

In [56]:
wf_frame_subset = wf_frame_1[1:5000]
wf_frame_subset

,0,1,2,3,4,5,6,7,8,9,10
459259,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
1083589,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
252642,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
6821,887,2014-03-14,15219,...,,15230,toolshed.g2.bx.psu.edu/repos/devteam/fastqc/f...,,f,t,
1229113,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
...,...,...,...,...,...,...,...,...,...,...,...
293631,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
431234,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f
2299184,125597,2022-01-27,1850173,...,,1850165,toolshed.g2.bx.psu.edu/repos/iuc/purge_dups/p...,1.2.5+galaxy4,f,t,f
1985563,84931,2021-03-18,1187845,addValue ...,1.0.0,1187846,toolshed.g2.bx.psu.edu/repos/bgruening/text_p...,0.1.0,f,t,
331020,1915,2015-01-19,29099,cat1 ...,1.0.0,29099,cat1 ...,1.0.0,f,t,f

In [55]:
wf_frame_subset.to_csv("../data/wf_frame_subset_march_22_5000.csv", index=None, header=None)

In [26]:
wf_path_old = "../data/worflow-connection-20-04.tsv"

wf_old = pd.read_csv(wf_path_old, sep="\t")

In [27]:
wf_old

,3,2013-02-07 16:48:46.721866,5,Grep1,1.0.1,7,Remove beginning1,1.0.0,f,t,f.1
0,3,2013-02-07 16:48:46.721866,6,Cut1,1.0.1,8,addValue,1.0.0,f,t,f
1,3,2013-02-07 16:48:46.721866,7,Remove beginning1,1.0.0,9,Cut1,1.0.1,f,t,f
2,3,2013-02-07 16:48:46.721866,7,Remove beginning1,1.0.0,6,Cut1,1.0.1,f,t,f
3,3,2013-02-07 16:48:46.721866,8,addValue,1.0.0,11,Paste1,1.0.0,f,t,f
4,3,2013-02-07 16:48:46.721866,9,Cut1,1.0.1,11,Paste1,1.0.0,f,t,f
...,...,...,...,...,...,...,...,...,...,...,...
746133,50779,2020-04-27 14:36:39.197104,727112,Cut1,NaN,727113,toolshed.g2.bx.psu.edu/repos/devteam/intersect...,NaN,f,f,NaN
746134,50779,2020-04-27 14:36:39.197104,727111,toolshed.g2.bx.psu.edu/repos/devteam/column_ma...,NaN,727112,Cut1,NaN,f,f,NaN
746135,50779,2020-04-27 14:36:39.197104,727110,toolshed.g2.bx.psu.edu/repos/devteam/column_ma...,NaN,727111,toolshed.g2.bx.psu.edu/repos/devteam/column_ma...,NaN,f,f,NaN
746136,50779,2020-04-27 14:36:39.197104,727108,NaN,NaN,727114,toolshed.g2.bx.psu.edu/repos/devteam/intersect...,NaN,f,f,NaN
746137,50779,2020-04-27 14:36:39.197104,727108,NaN,NaN,727113,toolshed.g2.bx.psu.edu/repos/devteam/intersect...,NaN,f,f,NaN

In [61]:
tool_popu_path = "../data/tool-popularity_Feb_22_12.csv"
tool_popu = pd.read_csv(tool_popu_path, sep="|", header=None)
tool_popu

,0,1,2
0,...,month,count
1,----------------------------------------------...,NaN,NaN
2,toolshed.g2.bx.psu.edu/repos/iuc/snpsift/snpS...,2022-02-01,67151
3,toolshed.g2.bx.psu.edu/repos/devteam/column_m...,2022-02-01,50054
4,upload1 ...,2022-02-01,43169
...,...,...,...
27203,toolshed.g2.bx.psu.edu/repos/iuc/hmmer_jackhm...,2021-02-01,1
27204,toolshed.g2.bx.psu.edu/repos/galaxyp/openms_h...,2021-02-01,1
27205,toolshed.g2.bx.psu.edu/repos/iuc/circos/circo...,2021-02-01,1
27206,toolshed.g2.bx.psu.edu/repos/bgruening/chembl...,2021-02-01,1
27207,(27205 rows),NaN,NaN

In [62]:
tool_popu_new = tool_popu[2:len(tool_popu.index) - 1]
tool_popu_new

,0,1,2
2,toolshed.g2.bx.psu.edu/repos/iuc/snpsift/snpS...,2022-02-01,67151
3,toolshed.g2.bx.psu.edu/repos/devteam/column_m...,2022-02-01,50054
4,upload1 ...,2022-02-01,43169
5,toolshed.g2.bx.psu.edu/repos/bgruening/text_p...,2022-02-01,39139
6,Cut1 ...,2022-02-01,29046
...,...,...,...
27202,toolshed.g2.bx.psu.edu/repos/devteam/emboss_5...,2021-02-01,1
27203,toolshed.g2.bx.psu.edu/repos/iuc/hmmer_jackhm...,2021-02-01,1
27204,toolshed.g2.bx.psu.edu/repos/galaxyp/openms_h...,2021-02-01,1
27205,toolshed.g2.bx.psu.edu/repos/iuc/circos/circo...,2021-02-01,1
27206,toolshed.g2.bx.psu.edu/repos/bgruening/chembl...,2021-02-01,1

In [64]:
tool_popu_new.to_csv("../data/tool_popularity_march_22.csv", index=None, header=None)